# Generated by Django 4.1.3 on 2023-08-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_alter_todolist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='task_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='task',
            field=models.CharField(max_length=300),
        ),
    ]
